In [1]:
#NumPy, short for Numerical Python, is a fundamental library for scientific computing and data analysis in Python. Here are some key purposes and advantages of using NumPy:

#Purpose of NumPy
#@Efficient Array Computations: NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
#@Foundation for Other Libraries: Many other scientific computing libraries, such as Pandas, SciPy, and Matplotlib, are built on top of NumPy, making it a cornerstone of the Python data science ecosystem1.
#Advantages of NumPy
#1Performance: NumPy is highly optimized for numerical operations. It uses pre-compiled C code, which makes array operations significantly faster than using Python lists1.
#2Memory Efficiency: NumPy arrays consume less memory compared to Python lists. This is because NumPy arrays are stored in contiguous blocks of memory, which allows for efficient access and manipulation2.
#3Vectorization: NumPy allows for vectorized operations, which means you can perform element-wise operations on entire arrays without the need for explicit loops. This not only makes the code more readable but also faster2.
#4Broadcasting: NumPy supports broadcasting, a powerful mechanism that allows arithmetic operations on arrays of different shapes. This feature simplifies the code and enhances performance2.
#5Integration with Other Libraries: NumPy seamlessly integrates with other scientific computing libraries, making it easier to perform complex data analysis and visualization tasks3.
##Enhancing Python’s Capabilities
#1Mathematical Functions: NumPy provides a wide range of mathematical functions, including trigonometric, statistical, and algebraic operations, which are not available in standard Python3.
#2Linear Algebra: It includes functions for linear algebra operations, such as matrix multiplication, eigenvalue computation, and singular value decomposition3.
#3Random Number Generation: NumPy has a robust random number generation module, which is essential for simulations and probabilistic modeling3.
##In summary, NumPy enhances Python’s capabilities by providing efficient, memory-saving, and high-performance tools for numerical operations, making it indispensable for scientific computing and data analysis.'''



In [2]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
##np.mean()
#Syntax: np.mean(arr, axis=None)
#arr: The input array.
#axis: Axis along which the means are computed. If not specified, the mean of the flattened array is calculated.
#Weights: Does not support weights; all elements are considered equally.
#Use Case: Use np.mean() when you need to calculate the simple arithmetic mean of an array without considering any weights.
##np.average()
#Purpose: Calculates the weighted average of the elements in an array.
#Syntax: np.average(arr, axis=None, weights=None)
#arr: The input array.
#axis: Axis along which the averages are computed. If not specified, the average of the flattened array is calculated.
#weights: An array of weights associated with the values in arr. If not specified, it calculates the simple arithmetic mean, similar to np.mean().
#Weights: Supports weights, allowing for the calculation of a weighted average.
#Use Case: Use np.average() when you need to calculate a weighted average, where different elements have different levels of importance.
##Comparison Example

import numpy as np

data = [1, 2, 3, 4, 5]

# Using np.mean()
mean_value = np.mean(data)
print("Mean:", mean_value)  

# Using np.average() without weights
average_value = np.average(data)
print("Average:", average_value)  

# Using np.average() with weights
weights = [1, 2, 3, 4, 5]
weighted_average_value = np.average(data, weights=weights)
print("Weighted Average:", weighted_average_value)  


Mean: 3.0
Average: 3.0
Weighted Average: 3.6666666666666665


In [5]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays
#1. Using Slicing
#Slicing is a straightforward way to reverse arrays.

#1D Array


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)  # Output: [1, 2, 3, 4, 5]
print("Reversed array:", reversed_arr)  # Output: [5, 4, 3, 2, 1]

#2D Array


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr = arr[::-1, ::-1]
print("Original array:\n", arr)

print("Reversed array:\n", reversed_arr)


#2. Using np.flip()


#1D Array

reversed_arr = np.flip(arr)
print("Reversed array using np.flip:", reversed_arr)  


reversed_arr = np.flip(arr, axis=0)  # Reverse along rows
print("Reversed along rows:\n", reversed_arr)

reversed_arr = np.flip(arr, axis=1)  # Reverse along columns
print("Reversed along columns:\n", reversed_arr)


#. Using np.flipud() and np.fliplr()
#These functions are specialized for flipping arrays vertically and horizontally.

#2D Array


reversed_arr = np.flipud(arr)  # Flip vertically
print("Flipped vertically:\n", reversed_arr)


reversed_arr = np.fliplr(arr)  # Flip horizontally
print("Flipped horizontally:\n", reversed_arr)


#This method flattens the array into a 1D array and then reverses it.

#2D Array


flattened_arr = arr.flatten()[::-1]
print("Flattened and reversed array:", flattened_arr)



Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed array using np.flip: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped vertically:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped horizontally:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flattened and reversed array: [9 8 7 6 5 4 3 2 1]


In [8]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
#in memory management and performance.
##Determining the Data Type of Elements in a NumPy Array
#To determine the data type of elements in a NumPy array, you can use the dtype attribute. This attribute provides information about the type of elements stored in the array.



import numpy as np

# Create an array of integers
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Data type:", arr.dtype) 

# Create an array of floats
arr_float = np.array([1.0, 2.0, 3.0])
print("Array:", arr_float)
print("Data type:", arr_float.dtype)  



##1. Memory Allocation
#Efficiency: Different data types require different amounts of memory. For example, an int32 type uses 4 bytes, while a float64 type uses 8 bytes. Choosing the appropriate data type ensures efficient memory usage1.
#Optimization: Using smaller data types for large datasets can significantly reduce memory consumption, which is especially important in environments with limited resources.
#2. Performance
#Speed: Operations on smaller data types are generally faster because they require less memory bandwidth and cache usage. For instance, arithmetic operations on int32 are faster than on int642.
#Vectorization: NumPy leverages vectorized operations, which are optimized for specific data types. Using the correct data type can enhance the performance of these operations.
#3. Data Integrity
#Precision: Different data types offer different levels of precision. For example, float32 provides less precision than float64. Choosing the right data type ensures that calculations are accurate and data integrity is maintained3.
#Compatibility: Ensuring that data types are compatible with other systems or libraries can prevent errors and improve interoperability.
#Example of Memory and Performance Impact


import numpy as np
import time

# Large array of integers
large_int_array = np.arange(1e7, dtype='int32')
start_time = time.time()
sum_int = np.sum(large_int_array)
print("Sum of int32 array:", sum_int)
print("Time taken for")


Array: [1 2 3 4 5]
Data type: int64
Array: [1. 2. 3.]
Data type: float64
Sum of int32 array: 49999995000000
Time taken for


In [1]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?




In [3]:
##NumPy ndarrays (N-dimensional arrays) are a core feature of the NumPy library, designed for efficient numerical computation. Here are some key features and differences compared to standard Python lists:

## Features of NumPy ndarrays:
#1Homogeneous Data: All elements in an ndarray are of the same data type, ensuring efficient memory usage and performance1.
#2N-Dimensional: ndarrays can have multiple dimensions (1D, 2D, 3D, etc.), making them suitable for complex data structures like matrices and tensors1.
#3Fixed Size: The size of an ndarray is fixed at creation. Changing the size requires creating a new array2.
#4Vectorized Operations: NumPy supports element-wise operations and broadcasting, allowing for efficient and concise mathematical computations without explicit loops3.
#5Advanced Indexing and Slicing: ndarrays support sophisticated indexing and slicing techniques, enabling easy manipulation of array subsets1.
#6Built-in Functions: NumPy provides a wide range of functions for mathematical operations, linear algebra, random number generation, and more3.
##Differences from Standard Python Lists:
#1Performance: ndarrays are more efficient in terms of speed and memory usage due to their homogeneous nature and optimized C-based implementation1.
#1Functionality: NumPy offers a rich set of functions for array manipulation and mathematical operations, which are not available for standard Python lists3.
#2Memory Layout: ndarrays store elements in contiguous memory locations, which enhances performance for large datasets2.
#3Fixed Size: Unlike Python lists, which can grow dynamically, ndarrays have a fixed size. Modifying the size requires creating a new array2.
#$Data Type Consistency: All elements in an ndarray must be of the same data type, whereas Python lists can contain elements of different types1.




import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Type:", type(arr))
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)



Array:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64


In [4]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here are some key reasons why:

#1. Memory Efficiency

#Homogeneous Data Types: All elements in a NumPy array are of the same data type, which allows for more efficient storage and access2.
#2. Speed

#Optimized C Implementation: Many NumPy operations are implemented in C, which is faster than Python’s interpreted code3.
#3. Functionality
##Rich Mathematical Functions: NumPy provides a wide range of built-in functions for mathematical, statistical, and linear algebra operations, which are optimized for performance4.
#Broadcasting: This feature allows NumPy to perform operations on arrays of different shapes and sizes without the need for explicit resizing2.
##4. Ease of Use
##Concise Syntax: NumPy’s syntax for array operations is more concise and closer to mathematical notation, making the code easier to write and read2.
##Performance Comparison Example


import numpy as np
import time

# Using NumPy arrays
array_size = 1000000
numpy_array = np.arange(array_size)
start_time = time.time()
numpy_array = numpy_array * 2
print("NumPy array time:", time.time() - start_time)

# Using Python lists
python_list = list(range(array_size))
start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python list time:", time.time() - start_time)


NumPy array time: 0.003922224044799805
Python list time: 0.16055607795715332


In [5]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

In [6]:
#The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. Here’s a comparison and examples to illustrate their usage:

#vstack()
#Purpose: Stacks arrays in sequence vertically (row-wise).
#Axis: Equivalent to concatenation along the first axis (axis=0).
#Usage: Useful for adding rows to an existing array.


import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking arrays vertically
result = np.vstack((a, b))
print(result)



##hstack()
#Purpose: Stacks arrays in sequence horizontally (column-wise).
#Axis: Equivalent to concatenation along the second axis (axis=1).
#Usage: Useful for adding columns to an existing array.


import numpy as np

# Creating two 2D arrays
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Stacking arrays horizontally
result = np.hstack((a, b))
print(result)




##Key Differences:
"""Direction:
vstack(): Stacks arrays vertically (adds rows).
hstack(): Stacks arrays horizontally (adds columns).
Axis:
vstack(): Concatenates along the first axis (axis=0).
hstack(): Concatenates along the second axis (axis=1).
Shape Requirements:
vstack(): Arrays must have the same number of columns.
hstack(): Arrays must have the same number of rows."""


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


'Direction:\nvstack(): Stacks arrays vertically (adds rows).\nhstack(): Stacks arrays horizontally (adds columns).\nAxis:\nvstack(): Concatenates along the first axis (axis=0).\nhstack(): Concatenates along the second axis (axis=1).\nShape Requirements:\nvstack(): Arrays must have the same number of columns.\nhstack(): Arrays must have the same number of rows.'

In [7]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
#array dimensions.

In [1]:

#fliplr()
#Function: Flips the array left to right.
#Axis: Operates along the horizontal axis (axis 1).
#Effect on 2D Arrays: Reverses the order of columns while keeping the rows intact.


import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.fliplr(a))


#flipud()
#Function: Flips the array upside down.
#Axis: Operates along the vertical axis (axis 0).
#Effect on 2D Arrays: Reverses the order of rows while keeping the columns intact.


import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.flipud(a))

##Effects on Higher Dimensions
#3D Arrays:
#fliplr(): Reverses the order of elements along the second axis (axis 1).
#flipud(): Reverses the order of elements along the first axis (axis 0).

#fliplr(): Think of it as flipping the array from left to right, affecting columns.
#flipud(): Think of it as flipping the array from top to bottom, affecting rows.
#These functions are particularly useful for image processing, data manipulation, and other array-based operations12.


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
#The array_split() method in NumPy is used to split an array into multiple sub-arrays. It’s particularly useful when you need to divide an array into parts that may not be of equal size. Here’s a detailed look at its functionality and how it handles uneven splits:

#Functionality
#Syntax: numpy.array_split(ary, indices_or_sections, axis=0)
#ary: The input array to be split.
##indices_or_sections: If an integer, it indicates the number of equal or near-equal sub-arrays to create. If a list of sorted integers, it specifies the points at which to split the array.
#axis: The axis along which to split the array (default is 0).
#Handling Uneven Splits
#When the array cannot be evenly divided by the specified number of splits, array_split() ensures that the sub-arrays are as equal in size as possible. It distributes the remainder elements across the sub-arrays.



import numpy as np

# Create an array of 9 elements
a = np.arange(9)

# Split the array into 4 parts
result = np.array_split(a, 4)
print(result)


#Comparison with split()
#split(): Requires that the array be evenly divisible by the number of splits, otherwise it raises an error.
#array_split(): Allows for uneven splits, making it more flexible for cases where equal division isn’t possible3.




[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [7]:
#Vectorization in NumPy
#Vectorization refers to the process of performing operations on entire arrays rather than individual elements. This approach leverages NumPy’s optimized C and Fortran libraries, making operations much faster compared to using Python loops.

##Benefits:
#Speed: Vectorized operations are significantly faster because they avoid the overhead of Python loops.
#Simplicity: Code is more concise and easier to read.


import numpy as np

# Using vectorization to add two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # Vectorized addition
print(c)



#Broadcasting in NumPy
#Broadcasting allows NumPy to perform operations on arrays of different shapes. It “stretches” the smaller array across the larger array so that they have compatible shapes for element-wise operations.

#Rules:
##If the arrays differ in their number of dimensions, the shape of the smaller array is padded with ones on its left side.
3#If the shape of the arrays does not match in a dimension, the array with shape 1 in that dimension is stretched to match the other shape.
##If the shapes are incompatible, a ValueError is raised.


import numpy as np

# Broadcasting a scalar to an array
a = np.array([1, 2, 3])
b = 2
c = a * b  # Broadcasting
print(c)

##Contribution to Efficient Array Operations
#Vectorization:
##Reduces Overhead: By eliminating Python loops, vectorization reduces the overhead associated with loop control and iteration.
#Optimized Computation: Operations are executed in compiled code, which is much faster than interpreted Python code.
#Broadcasting:
#Memory Efficiency: Broadcasting avoids making unnecessary copies of data, thus saving memory.
#Simplifies Code: Allows for more intuitive and concise code when dealing with arrays of different shapes.



[5 7 9]
[2 4 6]


In [6]:
import numpy as np
array=np.random.randint(1,101,size=(3,3))
transposed_array=array
print("\ntransposed array:")
print("transposed array")





transposed array:
transposed array


In [1]:
import numpy as np

# Create a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("1D array:")
print(array_1d)
print("\n2x5 array:")
print(array_2x5)
print("\n5x2 array:")
print(array_5x2)

1D array:
[0 1 2 3 4 5 6 7 8 9]

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 array with random float values:")
print(array_4x4)
print("\n6x6 array with a border of zeros:")
print(array_6x6)

4x4 array with random float values:
[[0.06613654 0.66964166 0.46904592 0.90890981]
 [0.96210437 0.54710598 0.8054433  0.37106212]
 [0.76259956 0.3143667  0.28595302 0.24356276]
 [0.42562671 0.47751881 0.29527252 0.6962513 ]]

6x6 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06613654 0.66964166 0.46904592 0.90890981 0.        ]
 [0.         0.96210437 0.54710598 0.8054433  0.37106212 0.        ]
 [0.         0.76259956 0.3143667  0.28595302 0.24356276 0.        ]
 [0.         0.42562671 0.47751881 0.29527252 0.6962513  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

print("Original array:")
print(array)
print("\nUppercase array:")
print(uppercase_array)
print("\nLowercase array:")
print(lowercase_array)
print("\nTitle case array:")
print(titlecase_array)

Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Title case array:
['Python' 'Numpy' 'Pandas']


In [6]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original array:")
print(words)
print("\nArray with spaces between characters:")
print(spaced_words)

Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise addition:")
print(addition)
print("\nElement-wise subtraction:")
print(subtraction)
print("\nElement-wise multiplication:")
print(multiplication)
print("\nElement-wise division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random integers array:")
print(random_integers)
print("\nPrime numbers in the array:")
print(prime_numbers)





Random integers array:
[821 927  90 941 271 364 716 734 100 492 163 954 674 275 550 245 981 136
 993 257 453  24 475  32  77 487 649 812 460 710 215 259 219 243 789 648
 105 941 939 822 320  28 265 975 773 500 928 819 674 533 232 935 104 998
 352 966  48  29 512 488 797 344 473 421  99 381  18 650 185 201 800  77
 758 737 771 984  43 235 931  83 828 694 890 230 962 723 288 530 139 767
 851 783 211 189 466 104 477 350 369 228]

Prime numbers in the array:
[821, 941, 271, 163, 257, 487, 941, 773, 29, 797, 421, 43, 83, 139, 211]


In [10]:
import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
# For simplicity, let's use random temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.uniform(20, 35, 30)

# Calculate the weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("Daily temperatures for a month:")
print(daily_temperatures)
print("\nWeekly averages:")
print(weekly_averages)

Daily temperatures for a month:
[22.74743712 29.70591981 27.55177517 30.07659458 32.47656609 23.97333984
 31.19991442 23.47984514 20.21232353 34.06710526 28.5908305  32.65611742
 26.78276441 20.83296795 30.30928329 27.29197729 31.06627661 20.20305348
 28.58246476 31.91877546 32.81249065 23.82422727 21.24682307 32.94612767
 22.6388993  32.96972307 33.46230552 22.99903827 30.3096807  34.1200901 ]

Weekly averages:
[28.24736386181818, 26.660279172262353, 28.883474506807495, 27.15530631090553, 32.21488540289624]
